#!/usr/bin/env python
import os, sys, shutil
from common import runLocalCommand, verifyPassword
import pexpect, getpass

def runSysConfigCommand(command):
  print "RUNNING COMMAND: "  + command
  p = pexpect.spawn(command,timeout=7200)
  while True:
    i = p.expect([r'\[sudo\] password.*', r'.*\[Y\/n\]','.+\n', '.+', pexpect.EOF])
    if i == 0:
      print p.after
      p.sendline(PASSWORD)
    elif i == 1:
      print p.after
      p.sendline("Y")
    if i == 2: print p.after.strip()
    if i == 3: 
      sys.stdout.write('\r' + p.after.strip())
      sys.stdout.flush()
    if i == 4: break


NAO_HOME = os.environ['NAO_HOME'] = '/home/' + os.environ['USER'] + '/nao/trunk'
os.chdir(NAO_HOME + '/install')
os.system('./install_fft')
os.system('echo export NAO_HOME=~/nao/trunk >> ~/.bashrc')
os.system('echo source \$NAO_HOME/install/bashrc_addenda >> ~/.bashrc')
os.system('qitoolchain create atom ~/nao/trunk/naoqi/crosstoolchain/atom/toolchain.xml')
os.system('qibuild add-config atom -t atom')
