#!/usr/bin/env sh
set -e
sudo apt-get install -y build-essential cmake ccache libqt4-dev libqt4-core libqt4-opengl-dev subversion swig2.0 lua5.1 cmake-curses-gui libmpfr-dev libqwt5-qt4-dev libdevil-dev libode-dev libnotify-bin git fping gfortran doxygen qt4-designer mpg123 python-pip

sudo apt-get install unity-gtk2-module:i386
